version: '3.7'

services:
    microservice:
        build:
            context: .
        image: microservice
        container_name: microservice
        restart: unless-stopped
        ports:
            - "8000:8000"
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped

        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        ports:
            - "6379:6379"
        command: redis-server /usr/local/etc/redis/redis.conf